---
- hosts: gluster-server
  become: yes
  become_method: sudo
  tasks:
    - name: Install software-properties-common
      apt:
        name: software-properties-common
        state: present
    - name: Install glusterfs-server
      apt:
        name: glusterfs-server
        state: present

    - name: Make sure glusterd service is running
      ansible.builtin.systemd:
        state: started
        enabled: yes
        name: glusterd

- hosts: gluster-client
  become: yes
  become_method: sudo
  tasks:
    - name: Install glusterfs-client
      apt:
        name: glusterfs-client
        state: present
    - name: Install samba
      apt:
        name: samba, samba-common-bin
        state: present


