---
- hosts: gluster-server
  become: yes
  become_method: sudo
  tasks:
    - name: Install software-properties-common
      apt:
        name: software-properties-common
        state: present
    - name: Install glusterfs-server
      apt:
        name: glusterfs-server
        state: present

- hosts: gluster-client
  become: yes
  become_method: sudo
  tasks:
    - name: Install glusterfs-client
      apt:
        name: glusterfs-client
        state: present
