---
- hosts: gluster-server
  become: yes
  become_method: sudo
  tasks:
    - name: Create StoragePool/gluster/opera
      command: zfs create StoragePool/gluster/opera
      register: command_output
      args:
        creates: /StoragePool/gluster/opera

    - name: Creates brick directory
      file:
        path: /StoragePool/gluster/opera/brick
        owner: root
        group: root
        mode: '1777'
        state: directory

    - name: Create StoragePool/gluster/test
      command: zfs create StoragePool/gluster/test
      register: command_output
      args:
        creates: /StoragePool/gluster/test

    - name: Creates brick directory
      file:
        path: /StoragePool/gluster/test/brick
        owner: root
        group: root
        mode: '1777'
        state: directory




- hosts: gluster-client
  become: yes
  become_method: sudo
  tasks:
    - name: create gluster volume with multiple bricks
      gluster.gluster.gluster_volume:
        state: present
        name: opera
        disperses: 3
        bricks: /StoragePool/gluster/opera/brick
        cluster:
          - storage2
          - storage3
          - storage4
      run_once: true

    - name: create gluster volume with multiple bricks
      gluster.gluster.gluster_volume:
        state: present
        name: test
        bricks: /StoragePool/gluster/test/brick
        cluster:
          - storage2
          - storage3
          - storage4
      run_once: true
