---
- hosts: gluster-server
  become: yes
  become_method: sudo
  tasks:
    - lineinfile:
      path: /etc/hosts
      regexp: '^192\.168\.10\.178'
      line: '192.168.10.178 storage1'
      owner: root
      group: root
      mode: 0644
    - lineinfile:
      path: /etc/hosts
      regexp: '^192\.168\.10\.182'
      line: '192.168.10.182 storage2'
      owner: root
      group: root
      mode: 0644
    - lineinfile:
      path: /etc/hosts
      regexp: '^192\.168\.10\.183'
      line: '192.168.10.183 storage3'
      owner: root
      group: root
      mode: 0644
    - lineinfile:
      path: /etc/hosts
      regexp: '^192\.168\.10\.181'
      line: '192.168.10.181 storage4'
      owner: root
      group: root
      mode: 0644