---
- hosts: nvme
  become: yes
  become_method: sudo
  tasks:
    - name: Create StoragePool
      command: zpool create StoragePool /dev/nvme0n1
      register: command_output
      args:
        creates: /StoragePool

    - name: Create StoragePool - command output
      ansible.builtin.debug:
        var: command_output.stdout_lines

    - name: Set StoragePool Compression
      command: zfs set compression=lz4 StoragePool
