---
- hosts: zfs
  become: yes
  become_method: sudo
  tasks:
    - name: Ansible apt install git
      apt:
        name: git
        state: present
    - name: Ansible apt install raspberrypi-kernel-headers
      apt:
        name: raspberrypi-kernel-headers
        state: present

    - name: Ansible apt install zfs-dkms 
      apt:
        name: zfs-dkms 
        state: present

    - name: Ansible apt install zfsutils-linux 
      apt:
        name: zfsutils-linux 
        state: present

    - name: Reboot the Debian or Ubuntu server
      reboot:
        msg: "Reboot initiated by Ansible due to kernel updates"
        connect_timeout: 5
        reboot_timeout: 300
        pre_reboot_delay: 0
        post_reboot_delay: 30
        test_command: uptime